// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9TCFjUZaDR6z6aiqqOmyWT1mMC9G-R4',
    appId: '1:852581253899:web:ce8654e45920f32140580e',
    messagingSenderId: '852581253899',
    projectId: 'fluttersqyipssi2023',
    authDomain: 'fluttersqyipssi2023.firebaseapp.com',
    storageBucket: 'fluttersqyipssi2023.appspot.com',
    measurementId: 'G-L9S3MTCY7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wxIYt6Edq2sDSuXK7C7i8NTTB4Mqq08',
    appId: '1:852581253899:android:cb0906e6d28c1d2240580e',
    messagingSenderId: '852581253899',
    projectId: 'fluttersqyipssi2023',
    storageBucket: 'fluttersqyipssi2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD62q3qllSDaXL0eEw_dGPEg9yKHbQXRPg',
    appId: '1:852581253899:ios:c1729733dd8bd1b340580e',
    messagingSenderId: '852581253899',
    projectId: 'fluttersqyipssi2023',
    storageBucket: 'fluttersqyipssi2023.appspot.com',
    iosClientId: '852581253899-6cf9rdtv5mpcerlvgh776n7o1fr6j4li.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD62q3qllSDaXL0eEw_dGPEg9yKHbQXRPg',
    appId: '1:852581253899:ios:c1729733dd8bd1b340580e',
    messagingSenderId: '852581253899',
    projectId: 'fluttersqyipssi2023',
    storageBucket: 'fluttersqyipssi2023.appspot.com',
    iosClientId: '852581253899-6cf9rdtv5mpcerlvgh776n7o1fr6j4li.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );
}
