// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd684RaJGFOQwSlet0_Yx-pqe0W3ChOug',
    appId: '1:492058107901:web:4a250e237b2f7456cb0394',
    messagingSenderId: '492058107901',
    projectId: 'flutter2023-110a6',
    authDomain: 'flutter2023-110a6.firebaseapp.com',
    storageBucket: 'flutter2023-110a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefeL15rFpyGHjvnm0Mlu_USlGZmxe_y8',
    appId: '1:492058107901:android:2834cbeca7f1e1f2cb0394',
    messagingSenderId: '492058107901',
    projectId: 'flutter2023-110a6',
    storageBucket: 'flutter2023-110a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKWEgHOBUKgBfCmvuIXVkM5cQxOGLIlSs',
    appId: '1:492058107901:ios:29a37a81555b124fcb0394',
    messagingSenderId: '492058107901',
    projectId: 'flutter2023-110a6',
    storageBucket: 'flutter2023-110a6.appspot.com',
    iosClientId: '492058107901-cesj4jep9np2o5ljqvuvfa6hs92oumke.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKWEgHOBUKgBfCmvuIXVkM5cQxOGLIlSs',
    appId: '1:492058107901:ios:29a37a81555b124fcb0394',
    messagingSenderId: '492058107901',
    projectId: 'flutter2023-110a6',
    storageBucket: 'flutter2023-110a6.appspot.com',
    iosClientId: '492058107901-cesj4jep9np2o5ljqvuvfa6hs92oumke.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );
}
